# Generated by Django 5.0.6 on 2024-06-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_is_deleted_alter_task_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Topshiriq', 'verbose_name_plural': 'Topshiriqlar'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_deleted',
            new_name='is_delete',
        ),
    ]
